"use client";

import { useState } from "react";
import {
  BarChart3, Clock3, Download, Eye, FilterX,
  Gift, MapPin, QrCode, Search, ShieldAlert, TicketCheck, Trophy,
  TrendingDown, TrendingUp, UserCheck, Users,
} from "lucide-react";

const menu=[
  {icon:"▦",label:"대시보드"},{icon:"◇",label:"상품관리",children:["상품목록","상품등록","일정표관리","요금관리"]},{icon:"▤",label:"예약관리",children:["예약접수현황","예약달력"]},{icon:"₩",label:"결제관리",children:["결제현황","취소/환불"]},{icon:"⇄",label:"정산관리",children:["정산현황","판매점정산","공급사정산"]},{icon:"♙",label:"회원관리",children:["웹회원","관리자/직원","그룹/권한"]},{icon:"▣",label:"판매점관리"},{icon:"⌂",label:"거래처관리"},{icon:"qr",label:"스탬프투어 관리",children:["스탬프투어 목록","관광지 관리","참여자·진행현황","인증 이력","완주·경품 관리","통계"]},{icon:"▥",label:"통계관리"},{icon:"◎",label:"운영관리",children:["팝업관리","알림관리","알림톡"]},{icon:"⚙",label:"시스템설정",children:["홈페이지설정","결제설정","기본설정"]},
];

const daily=[
  {day:"08.11",participants:64,auth:382,prevP:57,prevA:344},{day:"08.12",participants:72,auth:421,prevP:61,prevA:376},{day:"08.13",participants:68,auth:398,prevP:64,prevA:361},{day:"08.14",participants:81,auth:467,prevP:70,prevA:418},{day:"08.15",participants:103,auth:621,prevP:88,prevA:537},{day:"08.16",participants:118,auth:703,prevP:101,prevA:612},{day:"08.17",participants:127,auth:756,prevP:112,prevA:669},{day:"08.18",participants:96,auth:584,prevP:84,prevA:511},{day:"08.19",participants:109,auth:648,prevP:91,prevA:569},{day:"08.20",participants:73,auth:448,prevP:61,prevA:397},
];
const spots=[
  {rank:1,name:"고석정",total:1842,success:1769,fail:73,contribution:"22.8%",change:12.4},{rank:2,name:"소이산 모노레일",total:1621,success:1554,fail:67,contribution:"20.1%",change:8.7},{rank:3,name:"DMZ 두루미평화타운",total:1398,success:1342,fail:56,contribution:"17.3%",change:15.1},{rank:4,name:"철원역사문화공원",total:1284,success:1221,fail:63,contribution:"15.9%",change:6.2},{rank:5,name:"월정리역",total:1106,success:1019,fail:87,contribution:"13.7%",change:-3.8},{rank:6,name:"은하수교",total:1033,success:995,fail:38,contribution:"12.8%",change:9.4},{rank:7,name:"백마고지 전적지",total:957,success:912,fail:45,contribution:"11.9%",change:4.1},{rank:8,name:"직탕폭포",total:886,success:851,fail:35,contribution:"11.0%",change:7.6},
];
const weekdays=[{label:"월",value:1120},{label:"화",value:1074},{label:"수",value:1188},{label:"목",value:1246},{label:"금",value:1497},{label:"토",value:2264},{label:"일",value:1738}];
const hours=[{label:"09~11시",value:1475},{label:"11~13시",value:2281},{label:"13~15시",value:2842},{label:"15~17시",value:2517},{label:"17~19시",value:1012}];
const stages=[{label:"1곳 인증",value:219,color:"#94a3b8"},{label:"2~4곳 인증",value:643,color:"#4f7fb8"},{label:"완주",value:386,color:"#4f46e5"}];
const dropouts=[{label:"1곳",value:146,rate:"11.7%"},{label:"2곳",value:119,rate:"9.5%"},{label:"3곳",value:83,rate:"6.7%"},{label:"4곳",value:41,rate:"3.3%"},{label:"5곳 이상",value:12,rate:"1.0%"}];
const failures=[{label:"GPS 허용 범위 밖",value:184,color:"risk"},{label:"동일 관광지 중복",value:142,color:"warn"},{label:"인증 가능 시간 외",value:96,color:"slate"},{label:"비활성화 QR",value:51,color:"slate"},{label:"원거리 이동 의심",value:29,color:"risk"},{label:"동일 기기 다계정",value:18,color:"warn"}];

export default function StampTourStatisticsPage(){
  const [collapsed,setCollapsed]=useState(false),[expanded,setExpanded]=useState(["스탬프투어 관리"]);
  const [toast,setToast]=useState(""),[profileOpen,setProfileOpen]=useState(false),[noticeOpen,setNoticeOpen]=useState(false);
  const [tour,setTour]=useState("철원 DMZ 평화관광 스탬프투어"),[from,setFrom]=useState("2026-08-01"),[to,setTo]=useState("2026-08-20"),[spot,setSpot]=useState("전체 관광지"),[status,setStatus]=useState("운영 중"),[compare,setCompare]=useState(true);
  const [appliedTour,setAppliedTour]=useState(tour),[updated,setUpdated]=useState("2026.08.20 18:40"),[activeMetric,setActiveMetric]=useState<"participants"|"auth">("participants");
  const act=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2200)};
  const toggleMenu=(label:string)=>setExpanded(current=>current.includes(label)?current.filter(value=>value!==label):[...current,label]);
  const goChild=(child:string)=>child==="스탬프투어 목록"?window.location.assign("/stamp-tours"):child==="관광지 관리"?window.location.assign("/stamp-tours/attractions"):child==="참여자·진행현황"?window.location.assign("/stamp-tours/participants"):child==="인증 이력"?window.location.assign("/stamp-tours/verifications"):child==="완주·경품 관리"?window.location.assign("/stamp-tours/rewards"):child==="통계"?window.location.assign("/stamp-tours/statistics"):child==="상품목록"?window.location.assign("/products"):act(`${child} 화면은 다음 단계에서 제공될 예정입니다.`);
  const query=()=>{setAppliedTour(tour);setUpdated("2026.08.20 18:44");act("통계 조회 조건을 적용했습니다.")};
  const reset=()=>{setTour("철원 DMZ 평화관광 스탬프투어");setFrom("2026-08-01");setTo("2026-08-20");setSpot("전체 관광지");setStatus("운영 중");setCompare(true);setAppliedTour("철원 DMZ 평화관광 스탬프투어");act("통계 조건을 초기화했습니다.")};
  const download=()=>{const header=["순위","관광지명","전체 인증","정상 인증","실패 인증","완주 기여도","전 기간 대비 증감"];const csv="\uFEFF"+[header,...spots.map(row=>[row.rank,row.name,row.total,row.success,row.fail,row.contribution,`${row.change}%`])].map(row=>row.map(value=>`"${value}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="철원-DMZ-스탬프투어-통계.csv";link.click();URL.revokeObjectURL(url);act("스탬프투어 통계 엑셀 파일을 다운로드했습니다.")};
  const empty=appliedTour==="운영 준비중 투어 (데이터 없음)";
  const kpis=[["전체 참여자","1,248명","+13.2%",Users,"blue"],["신규 참여자","73명","전일 +19.7%",UserCheck,"indigo"],["누적 인증","10,127건","+11.8%",QrCode,"sky"],["완주자","386명","+42명",Trophy,"purple"],["완주율","30.9%","+2.6%p",TicketCheck,"green"],["경품 신청자","318명","완주자의 82.4%",Gift,"amber"],["평균 인증 관광지 수","4.2곳","+0.4곳",MapPin,"slate"],["이상 인증률","0.09%","전 기간 -0.03%p",ShieldAlert,"rose"]] as const;

  return <div className={`app-shell ${collapsed?"is-collapsed":""}`}>
    <aside className="sidebar"><div className="brand"><div className="brand-mark">A</div><div className="brand-copy"><strong>AOS</strong><span>TRAVEL ERP</span></div><button className="collapse" onClick={()=>setCollapsed(!collapsed)} aria-label="사이드바 접기">‹</button></div><nav aria-label="관리자 메뉴">{menu.map(item=><div className="nav-group" key={item.label}><button className={`nav-item ${item.label==="스탬프투어 관리"?"active":""}`} onClick={()=>item.label==="대시보드"?window.location.assign("/"):item.children?toggleMenu(item.label):act(`${item.label} 화면으로 이동합니다.`)}><span className="nav-icon">{item.icon==="qr"?<QrCode size={16}/>:item.icon}</span><span className="nav-label">{item.label}</span>{item.children&&<span className={`chevron ${expanded.includes(item.label)?"open":""}`}>⌄</span>}</button>{item.children&&expanded.includes(item.label)&&!collapsed&&<div className="subnav">{item.children.map(child=><button key={child} className={child==="통계"?"current":""} onClick={()=>goChild(child)}>{child}</button>)}</div>}</div>)}</nav><div className="sidebar-help"><span className="nav-icon">?</span><div><strong>업무지원센터</strong><p>평일 09:00–18:00</p></div></div></aside>
    <div className="workspace"><header className="topbar"><div className="breadcrumb"><span>스탬프투어 관리</span><b>/</b><strong>통계</strong></div><div className="top-actions"><label className="search"><span>⌕</span><input aria-label="빠른 검색" placeholder="예약번호, 고객명, 상품명 검색"/><kbd>⌘ K</kbd></label><button className="icon-btn">?</button><div className="dropdown-wrap"><button className="icon-btn notice" aria-label="알림" onClick={()=>{setNoticeOpen(!noticeOpen);setProfileOpen(false)}}>♢<i>5</i></button>{noticeOpen&&<div className="dropdown notice-menu"><div className="drop-head"><strong>알림</strong><button onClick={()=>setNoticeOpen(false)}>모두 읽음</button></div><button><span className="alert-dot warn"/><span>오늘 통계 집계가 완료되었습니다.<small>방금 전</small></span></button></div>}</div><div className="divider"/><div className="dropdown-wrap"><button className="profile" onClick={()=>{setProfileOpen(!profileOpen);setNoticeOpen(false)}}><span className="avatar">장</span><span><b>애비아넥스트</b><small>관리자 장윤호</small></span><em>⌄</em></button>{profileOpen&&<div className="dropdown profile-menu"><button>내 정보</button><button>환경설정</button><hr/><button className="logout">로그아웃</button></div>}</div></div></header>
      <main className="content statistics-content"><section className="page-head statistics-page-head"><div><h1>스탬프투어 통계</h1><p>참여·인증·완주·경품 운영성과를 기간과 관광지별로 분석합니다.</p></div><span><Clock3 size={12}/>최종 집계 {updated}</span></section>
        <section className="panel statistics-filter"><div className="statistics-filter-grid"><label><span>스탬프투어</span><select value={tour} onChange={event=>setTour(event.target.value)}><option>철원 DMZ 평화관광 스탬프투어</option><option>양평 자연휴양 산책 스탬프투어</option><option>운영 준비중 투어 (데이터 없음)</option></select></label><label className="statistics-period"><span>기간</span><div><input type="date" value={from} onChange={event=>setFrom(event.target.value)}/><em>~</em><input type="date" value={to} onChange={event=>setTo(event.target.value)}/></div></label><label><span>관광지</span><select value={spot} onChange={event=>setSpot(event.target.value)}><option>전체 관광지</option>{spots.map(row=><option key={row.name}>{row.name}</option>)}</select></label><label><span>운영상태</span><select value={status} onChange={event=>setStatus(event.target.value)}><option>전체</option><option>운영 예정</option><option>운영 중</option><option>일시중지</option><option>운영 종료</option></select></label><label className="comparison-toggle"><span>비교기간</span><button className={compare?"on":""} onClick={()=>setCompare(!compare)} role="switch" aria-checked={compare}><i/><b>{compare?"사용":"미사용"}</b></button></label></div><div className="statistics-filter-actions"><button className="secondary" onClick={reset}><FilterX size={14}/>초기화</button><button className="primary" onClick={query}><Search size={14}/>조회</button><button className="excel-button" onClick={download}><Download size={14}/>엑셀 다운로드</button></div></section>
        {empty?<section className="panel statistics-empty"><BarChart3 size={34}/><strong>조회할 통계 데이터가 없습니다.</strong><p>운영이 시작된 스탬프투어 또는 다른 기간을 선택해 주세요.</p><button className="secondary" onClick={reset}>기본 투어로 돌아가기</button></section>:<>
          <section className="statistics-kpis">{kpis.map(([title,value,change,Icon,color])=><div className={`statistics-kpi ${color}`} key={title}><div><small>{title}</small><strong>{value}</strong><em className={String(change).includes("-")?"down":"up"}>{String(change).includes("-")?<TrendingDown size={10}/>:<TrendingUp size={10}/>} {change}</em></div><i><Icon size={17}/></i></div>)}</section>
          <section className="panel trend-panel"><div className="statistics-panel-head"><div><h2>기간별 참여자·인증 추이</h2><p>2026.08.11~08.20 일별 집계</p></div><div className="statistics-segments"><button className={activeMetric==="participants"?"active":""} onClick={()=>setActiveMetric("participants")}>참여자</button><button className={activeMetric==="auth"?"active":""} onClick={()=>setActiveMetric("auth")}>인증</button><span><i className="current"/>조회기간</span>{compare&&<span><i className="previous"/>이전기간</span>}</div></div><div className="trend-summary"><div><span>{activeMetric==="participants"?"기간 참여자":"기간 인증"}</span><b>{activeMetric==="participants"?"911명":"5,428건"}</b><em>전 기간 대비 +{activeMetric==="participants"?"13.5":"11.8"}%</em></div><small>막대 위에 마우스를 올리면 일자별 수치를 확인할 수 있습니다.</small></div><div className="trend-chart"><div className="chart-axis"><span>100%</span><span>75%</span><span>50%</span><span>25%</span><span>0</span></div>{daily.map(row=>{const value=activeMetric==="participants"?row.participants:row.auth;const previous=activeMetric==="participants"?row.prevP:row.prevA;const max=activeMetric==="participants"?130:780;return <div className="trend-day" key={row.day}><div className="trend-bars"><button style={{height:`${value/max*100}%`}} data-tip={`${row.day} · ${value.toLocaleString()}${activeMetric==="participants"?"명":"건"}`} aria-label={`${row.day} ${value}`}/>{compare&&<button className="previous" style={{height:`${previous/max*100}%`}} data-tip={`${row.day} 이전기간 · ${previous.toLocaleString()}${activeMetric==="participants"?"명":"건"}`} aria-label={`${row.day} 이전기간 ${previous}`}/>}</div><span>{row.day}</span></div>})}</div></section>
          <div className="statistics-two-grid"><section className="panel chart-card"><div className="statistics-panel-head"><div><h2>관광지별 인증 건수와 방문 순위</h2><p>전체 10,127건 · 상위 5곳</p></div><span className="metric-change up">+11.8%</span></div><div className="rank-bars">{spots.slice(0,5).map(row=><button key={row.name} data-tip={`${row.name} · ${row.total.toLocaleString()}건 · 전 기간 대비 ${row.change>0?"+":""}${row.change}%`} onClick={()=>{setSpot(row.name);act(`${row.name} 기준으로 필터를 준비했습니다.`)}}><b>{row.rank}</b><span>{row.name}</span><i><em style={{width:`${row.total/spots[0].total*100}%`}}/></i><strong>{row.total.toLocaleString()}</strong><small className={row.change<0?"down":"up"}>{row.change>0?"+":""}{row.change}%</small></button>)}</div></section>
            <section className="panel chart-card"><div className="statistics-panel-head"><div><h2>요일별·시간대별 인증 현황</h2><p>주말 비중 39.5% · 13~15시 최다</p></div><div className="mini-legend"><span><i className="blue"/>요일</span><span><i className="indigo"/>시간대</span></div></div><div className="weekday-chart">{weekdays.map(row=><button key={row.label} data-tip={`${row.label}요일 · ${row.value.toLocaleString()}건`}><i style={{height:`${row.value/2264*100}%`}}/><span>{row.label}</span></button>)}</div><div className="time-bars">{hours.map(row=><button key={row.label} data-tip={`${row.label} · ${row.value.toLocaleString()}건`}><span>{row.label}</span><i><em style={{width:`${row.value/2842*100}%`}}/></i><b>{row.value.toLocaleString()}</b></button>)}</div></section>
          </div>
          <div className="statistics-two-grid"><section className="panel chart-card"><div className="statistics-panel-head"><div><h2>진행 단계별 참여자 분포</h2><p>전체 참여자 1,248명 기준</p></div></div><div className="stage-layout"><div className="stage-donut"><div><b>1,248</b><span>전체 참여자</span></div></div><div className="stage-list">{stages.map(row=><div key={row.label}><i style={{background:row.color}}/><span>{row.label}</span><b>{row.value.toLocaleString()}명</b><small>{(row.value/1248*100).toFixed(1)}%</small></div>)}</div></div></section>
            <section className="panel chart-card"><div className="statistics-panel-head"><div><h2>인증 개수별 이탈 현황</h2><p>최근 14일 추가 인증이 없는 참여자</p></div><span className="metric-change down">총 401명</span></div><div className="dropout-chart">{dropouts.map(row=><button key={row.label} data-tip={`${row.label} 인증 후 이탈 · ${row.value}명 (${row.rate})`}><span>{row.label}</span><i><em style={{width:`${row.value/146*100}%`}}/></i><b>{row.value}명</b><small>{row.rate}</small></button>)}</div></section>
          </div>
          <div className="statistics-two-grid"><section className="panel chart-card"><div className="statistics-panel-head"><div><h2>완주자와 미완주자 비교</h2><p>완주조건 8곳 중 5곳 이상 인증</p></div></div><div className="completion-compare"><div className="complete"><span><Trophy size={18}/></span><div><small>완주자</small><b>386명</b><em>30.9%</em></div><i><em style={{width:"30.9%"}}/></i><p>평균 인증 5.8곳 · 평균 완주 3.2일</p></div><div className="incomplete"><span><Users size={18}/></span><div><small>미완주자</small><b>862명</b><em>69.1%</em></div><i><em style={{width:"69.1%"}}/></i><p>평균 인증 2.6곳 · 최근 활동 4.7일 전</p></div></div></section>
            <section className="panel chart-card"><div className="statistics-panel-head"><div><h2>경품 신청 및 지급 현황</h2><p>완주자 386명 중 신청 318명</p></div></div><div className="reward-stat-summary"><div><Gift size={18}/><span><small>경품 신청률</small><b>82.4%</b></span><em>318명</em></div><i><em style={{width:"82.4%"}}/></i></div><div className="reward-stat-list">{[["지급 완료",184,"57.9%","green"],["발송·지급 대기",98,"30.8%","blue"],["확인 중",24,"7.5%","amber"],["반려",12,"3.8%","slate"]].map(([label,value,rate,color])=><div key={String(label)}><i className={String(color)}/><span>{label}</span><b>{value}명</b><small>{rate}</small></div>)}</div></section>
          </div>
          <section className="panel anomaly-stat-panel"><div className="statistics-panel-head"><div><h2>인증 실패·이상 인증 유형</h2><p>실패 520건 · 이상 인증 의심 47건</p></div><div className="mini-legend"><span><i className="slate"/>실패</span><span><i className="amber"/>주의</span><span><i className="rose"/>위험</span></div></div><div className="failure-grid">{failures.map(row=><button key={row.label} data-tip={`${row.label} · ${row.value}건`}><span>{row.label}</span><i><em className={row.color} style={{width:`${row.value/184*100}%`}}/></i><b>{row.value}건</b></button>)}</div></section>
          <section className="panel performance-panel"><div className="statistics-panel-head"><div><h2>관광지별 운영성과</h2><p>인증 품질과 완주 기여도를 관광지별로 비교합니다.</p></div><span>단위: 건, %</span></div><div className="performance-table-wrap"><table className="performance-table"><thead><tr>{["순위","관광지명","전체 인증","정상 인증","실패 인증","완주 기여도","전 기간 대비 증감","상세보기"].map(title=><th key={title}>{title}</th>)}</tr></thead><tbody>{spots.map(row=><tr key={row.name}><td><b className={`rank-number rank-${row.rank}`}>{row.rank}</b></td><td><strong>{row.name}</strong><small>SPOT-{String(row.rank).padStart(3,"0")}</small></td><td>{row.total.toLocaleString()}</td><td className="success-value">{row.success.toLocaleString()}</td><td>{row.fail.toLocaleString()}</td><td><span className="contribution"><i><em style={{width:row.contribution}}/></i><b>{row.contribution}</b></span></td><td><span className={`table-change ${row.change<0?"down":"up"}`}>{row.change>0?<TrendingUp size={11}/>:<TrendingDown size={11}/>} {row.change>0?"+":""}{row.change}%</span></td><td><button onClick={()=>{setSpot(row.name);act(`${row.name} 상세 통계 필터를 적용할 준비가 됐습니다.`)}}><Eye size={12}/>상세</button></td></tr>)}</tbody></table></div></section><footer>© 2026 AOS Travel ERP · AviaNext</footer>
        </>}
      </main></div>{toast&&<div className="toast"><span>✓</span>{toast}</div>}
  </div>;
}
