const A='assets/';
const imageFiles=['travel-01.jpeg','travel-02.jpg','travel-03.png','travel-04.jpg','travel-05.jpg','travel-06.jpg','travel-07.jpg','travel-08.jpg','travel-09.png','travel-10.jpg','travel-11.jpg','travel-12.jpg','travel-13.jpg','travel-14.jpg','travel-15.jpg','travel-16.jpg','travel-17.jpg','travel-18.jpg'];
const regions={일본:['도쿄','오사카','홋카이도','오키나와'],베트남:['다낭','나트랑','푸꾸옥','하노이'],태국:['방콕','파타야','푸켓','치앙마이'],유럽:['파리','로마','프라하','스위스']};
const quick=[['✈️','항공권'],['🏨','호텔'],['🌴','패키지'],['🚆','기차여행'],['🚌','버스여행'],['⛳','골프여행'],['🛳️','크루즈'],['🎁','상품권']];
document.querySelector('#quick').innerHTML=quick.map(([i,n],x)=>`<a href="${x?'service-ready.html':'products.html?category=flight'}"><i>${i}</i><span>${n}</span></a>`).join('');
const img=i=>A+imageFiles[i%imageFiles.length];
function cards(region='일본',offset=0){return regions[region].map((name,i)=>`<article class="card"><a href="product-detail.html?id=${18344+i}"><img src="${img(i+offset)}" alt="${name} 여행"><div class="card-body"><em>${region} · 항공포함</em><h3>${name}</h3><p>BEST ${name} 핵심 명소와 여유를 담은 ${i+3}박 ${i+4}일</p><strong class="price ${i?'empty':''}">${i?'가격 문의':'1,490,000원~'}</strong></div></a></article>`).join('')}
['wish-grid','popular-grid','recommend-grid','world-grid'].forEach((id,i)=>document.querySelector('#'+id).innerHTML=cards('일본',i*3));
document.querySelector('#circle-list').innerHTML=['도쿄 자유여행','오사카 미식여행','후쿠오카 힐링','오키나와 휴양','홋카이도 여행'].map((n,i)=>`<a class="circle-item" href="products.html?theme=${i}"><img src="${img(i+5)}" alt="${n}"><b>${n}</b><span>지금 가장 사랑받는 여행</span></a>`).join('');
document.querySelector('#mini-grid').innerHTML=['다낭 여행','나트랑 여행','푸꾸옥 여행','하노이 여행','호치민 여행','사파 여행'].map((n,i)=>`<a class="mini" href="products.html?theme=${i}"><img src="${img(i+8)}" alt="${n}"><div><b>${n}</b><p>가족과 함께하는 특별한 휴양</p></div></a>`).join('');
function features(region='일본'){return regions[region].map((n,i)=>`<a class="feature" href="product-detail.html?id=${18400+i}"><img src="${img(i+3)}" alt="${n}"><div><small>${region}</small><h3>${n}</h3><span>지금 떠나기 좋은 여행</span></div></a>`).join('')}
document.querySelector('#theme-grid').innerHTML=features();
document.querySelector('#poster-grid').innerHTML=['도쿄의 낮과 밤','오사카 미식 산책','홋카이도 자연'].map((n,i)=>`<a class="poster" href="product-detail.html?id=${18420+i}"><img src="${img(i+10)}" alt="${n}"><div><b>${n}</b><p>감각적인 여행의 순간</p></div></a>`).join('');
document.querySelector('#journey-grid').innerHTML=['베트남 여행','태국 여행','필리핀 여행','싱가포르 여행'].map((n,i)=>`<a class="journey" style="--accent:${['#19b6df','#22b887','#ff9d29','#8173ea'][i]}" href="products.html?journey=${i}"><small>DAY 0${i+1}</small><h3>${n}</h3><p>${n}의 대표 도시를 내 취향대로</p><img src="${img(i+12)}" alt="${n}"></a>`).join('');
document.querySelector('#rank-list').innerHTML=regions.일본.map((n,i)=>`<li><b>${i+1}</b><img src="${img(i+5)}" alt="${n}"><div><h3>${n}</h3><p>${n} ${i+2}박 ${i+3}일 자유여행</p></div><strong>${i?'가격 문의':'1,490,000원~'}</strong></li>`).join('');
document.querySelector('#gallery').innerHTML=['도쿄 자유여행','오사카 여행','후쿠오카 힐링','오키나와 휴양','홋카이도 여행'].map((n,i)=>`<a href="products.html?gallery=${i}"><img src="${img(i+1)}" alt="${n}"><span>${n}</span></a>`).join('');
document.querySelectorAll('.tabs').forEach(group=>group.addEventListener('click',e=>{if(e.target.tagName!=='BUTTON')return;group.querySelectorAll('button').forEach(b=>b.classList.remove('active'));e.target.classList.add('active');const target=document.querySelector('#'+group.dataset.target);if(!target)return;const region=e.target.textContent.trim();target.innerHTML=target.classList.contains('feature-grid')?features(region):target.classList.contains('rank-list')?regions[region].map((n,i)=>`<li><b>${i+1}</b><img src="${img(i+6)}" alt="${n}"><div><h3>${n}</h3><p>${n} 추천 일정</p></div><strong>가격 문의</strong></li>`).join(''):cards(region,regions.일본.indexOf(region)+2)}));
document.querySelector('.menu-toggle').addEventListener('click',e=>{const nav=document.querySelector('.gnb');nav.classList.toggle('open');const open=nav.classList.contains('open');e.currentTarget.setAttribute('aria-expanded',open);e.currentTarget.setAttribute('aria-label',open?'메뉴 닫기':'메뉴 열기')});
document.querySelectorAll('[data-scroll]').forEach(b=>b.addEventListener('click',()=>document.querySelector(b.dataset.scroll).scrollIntoView()));
document.querySelectorAll('[data-mood]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-mood]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('.mood-photos').style.transform=`translateX(${-Number(b.dataset.mood)*3}px)`}));
