"use client";

import { useMemo, useState } from "react";
import LiveStampTourPanel from "../LiveStampTourPanel";
import {
  AlertTriangle, CheckCircle2, ChevronLeft, ChevronRight, CircleHelp,
  Clock3, Eye, FilterX, Flag, Laptop, MapPin, QrCode, Search,
  ShieldAlert, ShieldCheck, Smartphone, XCircle,
} from "lucide-react";

const menu=[
  {icon:"▦",label:"대시보드"},{icon:"◇",label:"상품관리",children:["상품목록","상품등록","일정표관리","요금관리"]},{icon:"▤",label:"예약관리",children:["예약접수현황","예약달력"]},{icon:"₩",label:"결제관리",children:["결제현황","취소/환불"]},{icon:"⇄",label:"정산관리",children:["정산현황","판매점정산","공급사정산"]},{icon:"♙",label:"회원관리",children:["웹회원","관리자/직원","그룹/권한"]},{icon:"▣",label:"판매점관리"},{icon:"⌂",label:"거래처관리"},{icon:"qr",label:"스탬프투어 관리",children:["스탬프투어 목록","관광지 관리","참여자·진행현황","인증 이력","완주·경품 관리","통계"]},{icon:"▥",label:"통계관리"},{icon:"◎",label:"운영관리",children:["팝업관리","알림관리","알림톡"]},{icon:"⚙",label:"시스템설정",children:["홈페이지설정","결제설정","기본설정"]},
];

type Result="정상 인증"|"인증 실패";
type Anomaly="없음"|"동일 관광지 중복 시도"|"GPS 허용 범위 밖"|"비활성화 QR"|"인증 가능 시간 외"|"짧은 시간 내 원거리 이동"|"동일 기기 다계정 참여 의심";
type Review="미검수"|"정상"|"부정"|"확인 보류";
type RecordRow={id:number;number:string;date:string;participant:string;phone:string;spot:string;spotCode:string;result:Result;distance:string;distanceM:number;device:string;deviceType:"mobile"|"desktop";ip:string;anomaly:Anomaly;review:Review;lat:string;lng:string;spotLat:string;spotLng:string};

const records:RecordRow[]=[
  {id:1,number:"VRF-20260820-10328",date:"2026.08.20 18:36:24",participant:"샘플 사용자",phone:"010-0000-0000",spot:"고석정",spotCode:"SPOT-001",result:"정상 인증",distance:"32m",distanceM:32,device:"iPhone 15 · iOS 19",deviceType:"mobile",ip:"211.234.**.18",anomaly:"없음",review:"정상",lat:"38.186742",lng:"127.287914",spotLat:"38.186521",spotLng:"127.287663"},
  {id:2,number:"VRF-20260820-10327",date:"2026.08.20 18:31:09",participant:"샘플 사용자",phone:"010-0000-0000",spot:"월정리역",spotCode:"SPOT-004",result:"인증 실패",distance:"684m",distanceM:684,device:"Galaxy S25 · Android 17",deviceType:"mobile",ip:"223.38.**.91",anomaly:"GPS 허용 범위 밖",review:"미검수",lat:"38.308812",lng:"127.221904",spotLat:"38.314295",spotLng:"127.220304"},
  {id:3,number:"VRF-20260820-10326",date:"2026.08.20 18:28:43",participant:"샘플 사용자",phone:"010-0000-0000",spot:"은하수교",spotCode:"SPOT-008",result:"정상 인증",distance:"18m",distanceM:18,device:"iPhone 14 Pro · iOS 19",deviceType:"mobile",ip:"118.235.**.42",anomaly:"없음",review:"정상",lat:"38.207801",lng:"127.274216",spotLat:"38.207719",spotLng:"127.274054"},
  {id:4,number:"VRF-20260820-10325",date:"2026.08.20 18:26:12",participant:"샘플 사용자",phone:"010-0000-0000",spot:"소이산 모노레일",spotCode:"SPOT-002",result:"인증 실패",distance:"41m",distanceM:41,device:"Galaxy S24 · Android 16",deviceType:"mobile",ip:"106.101.**.77",anomaly:"동일 관광지 중복 시도",review:"정상",lat:"38.252412",lng:"127.199781",spotLat:"38.252231",spotLng:"127.199432"},
  {id:5,number:"VRF-20260820-10324",date:"2026.08.20 18:19:55",participant:"샘플 사용자",phone:"010-0000-0000",spot:"월정리역",spotCode:"SPOT-004",result:"인증 실패",distance:"27m",distanceM:27,device:"iPhone 13 · iOS 18",deviceType:"mobile",ip:"121.190.**.15",anomaly:"비활성화 QR",review:"확인 보류",lat:"38.314102",lng:"127.220477",spotLat:"38.314295",spotLng:"127.220304"},
  {id:6,number:"VRF-20260820-10323",date:"2026.08.20 17:58:37",participant:"샘플 사용자",phone:"010-0000-0000",spot:"고석정",spotCode:"SPOT-001",result:"인증 실패",distance:"55m",distanceM:55,device:"Chrome 140 · Windows",deviceType:"desktop",ip:"175.213.**.28",anomaly:"인증 가능 시간 외",review:"미검수",lat:"38.186831",lng:"127.288240",spotLat:"38.186521",spotLng:"127.287663"},
  {id:7,number:"VRF-20260820-10322",date:"2026.08.20 17:51:02",participant:"샘플 사용자",phone:"010-0000-0000",spot:"백마고지 전적지",spotCode:"SPOT-006",result:"정상 인증",distance:"63m",distanceM:63,device:"Galaxy Z Flip7 · Android 17",deviceType:"mobile",ip:"223.62.**.103",anomaly:"짧은 시간 내 원거리 이동",review:"미검수",lat:"38.316442",lng:"127.191182",spotLat:"38.316071",spotLng:"127.190614"},
  {id:8,number:"VRF-20260820-10321",date:"2026.08.20 17:43:29",participant:"샘플 사용자",phone:"010-0000-0000",spot:"철원역사문화공원",spotCode:"SPOT-005",result:"정상 인증",distance:"24m",distanceM:24,device:"iPhone 16 · iOS 19",deviceType:"mobile",ip:"211.36.**.204",anomaly:"동일 기기 다계정 참여 의심",review:"부정",lat:"38.214947",lng:"127.209071",spotLat:"38.214790",spotLng:"127.208894"},
  {id:9,number:"VRF-20260820-10320",date:"2026.08.20 17:39:18",participant:"샘플 사용자",phone:"010-0000-0000",spot:"직탕폭포",spotCode:"SPOT-007",result:"정상 인증",distance:"47m",distanceM:47,device:"Galaxy S25 · Android 17",deviceType:"mobile",ip:"117.111.**.64",anomaly:"없음",review:"정상",lat:"38.201229",lng:"127.286721",spotLat:"38.200915",spotLng:"127.286393"},
  {id:10,number:"VRF-20260820-10319",date:"2026.08.20 17:32:04",participant:"샘플 사용자",phone:"010-0000-0000",spot:"DMZ 두루미평화타운",spotCode:"SPOT-003",result:"인증 실패",distance:"1.2km",distanceM:1200,device:"iPhone 15 Pro · iOS 19",deviceType:"mobile",ip:"39.7.**.188",anomaly:"GPS 허용 범위 밖",review:"부정",lat:"38.282104",lng:"127.183412",spotLat:"38.291842",spotLng:"127.180235"},
  {id:11,number:"VRF-20260820-10318",date:"2026.08.20 17:24:51",participant:"샘플 사용자",phone:"010-0000-0000",spot:"소이산 모노레일",spotCode:"SPOT-002",result:"정상 인증",distance:"29m",distanceM:29,device:"Galaxy S23 · Android 16",deviceType:"mobile",ip:"106.102.**.17",anomaly:"없음",review:"정상",lat:"38.252389",lng:"127.199608",spotLat:"38.252231",spotLng:"127.199432"},
  {id:12,number:"VRF-20260820-10317",date:"2026.08.20 17:16:33",participant:"샘플 사용자",phone:"010-0000-0000",spot:"고석정",spotCode:"SPOT-001",result:"인증 실패",distance:"35m",distanceM:35,device:"iPhone 12 · iOS 18",deviceType:"mobile",ip:"211.234.**.75",anomaly:"동일 관광지 중복 시도",review:"미검수",lat:"38.186701",lng:"127.287850",spotLat:"38.186521",spotLng:"127.287663"},
];

const maskPhone=(phone:string)=>phone.replace(/(\d{3})-(\d{4})-(\d{4})/,"$1-****-$3");
const anomalyClass=(value:Anomaly)=>value==="없음"?"normal":value==="동일 관광지 중복 시도"||value==="인증 가능 시간 외"?"caution":"risk";

export default function VerificationHistoryPage(){
  const [collapsed,setCollapsed]=useState(false),[expanded,setExpanded]=useState(["스탬프투어 관리"]);
  const [toast,setToast]=useState(""),[profileOpen,setProfileOpen]=useState(false),[noticeOpen,setNoticeOpen]=useState(false);
  const [tour,setTour]=useState("철원 DMZ 평화관광 스탬프투어"),[spot,setSpot]=useState("전체"),[name,setName]=useState(""),[phone,setPhone]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[result,setResult]=useState("전체"),[anomaly,setAnomaly]=useState("전체"),[review,setReview]=useState("전체");
  const [applied,setApplied]=useState({spot:"전체",name:"",phone:"",from:"",to:"",result:"전체",anomaly:"전체",review:"전체"});
  const [selected,setSelected]=useState<RecordRow|null>(null),[page,setPage]=useState(1);
  const [judgement,setJudgement]=useState<"정상"|"부정"|"확인 보류">("확인 보류"),[reason,setReason]=useState(""),[memo,setMemo]=useState("");
  const [reasonError,setReasonError]=useState(false);
  const act=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2200)};
  const toggleMenu=(label:string)=>setExpanded(current=>current.includes(label)?current.filter(value=>value!==label):[...current,label]);
  const goChild=(child:string)=>child==="스탬프투어 목록"?window.location.assign("/stamp-tours"):child==="관광지 관리"?window.location.assign("/stamp-tours/attractions"):child==="참여자·진행현황"?window.location.assign("/stamp-tours/participants"):child==="인증 이력"?window.location.assign("/stamp-tours/verifications"):child==="완주·경품 관리"?window.location.assign("/stamp-tours/rewards"):child==="통계"?window.location.assign("/stamp-tours/statistics"):child==="상품목록"?window.location.assign("/products"):act(`${child} 화면은 다음 단계에서 제공될 예정입니다.`);
  const filtered=useMemo(()=>records.filter(row=>{
    const rowDate=row.date.slice(0,10).replaceAll(".","-");
    return (applied.spot==="전체"||row.spot===applied.spot)&&(!applied.name||row.participant.includes(applied.name))&&(!applied.phone||row.phone.replaceAll("-","").includes(applied.phone.replaceAll("-","")))&&(!applied.from||rowDate>=applied.from)&&(!applied.to||rowDate<=applied.to)&&(applied.result==="전체"||row.result===applied.result)&&(applied.anomaly==="전체"||row.anomaly===applied.anomaly)&&(applied.review==="전체"||row.review===applied.review);
  }),[applied]);
  const pageSize=6,totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)),visible=filtered.slice((page-1)*pageSize,page*pageSize);
  const search=()=>{setApplied({spot,name:name.trim(),phone:phone.trim(),from,to,result,anomaly,review});setPage(1);act("검색 조건을 적용했습니다.")};
  const reset=()=>{setSpot("전체");setName("");setPhone("");setFrom("");setTo("");setResult("전체");setAnomaly("전체");setReview("전체");setApplied({spot:"전체",name:"",phone:"",from:"",to:"",result:"전체",anomaly:"전체",review:"전체"});setPage(1);act("검색 조건을 초기화했습니다.")};
  const openDrawer=(row:RecordRow)=>{setSelected(row);setJudgement(row.review==="정상"||row.review==="부정"?row.review:"확인 보류");setReason("");setMemo("");setReasonError(false)};
  const moveRecord=(direction:number)=>{if(!selected)return;const index=filtered.findIndex(row=>row.id===selected.id);const next=filtered[index+direction];if(next)openDrawer(next)};
  const saveReview=()=>{if(!reason.trim()){setReasonError(true);return}act(`${judgement} 판정이 저장되었습니다.`);setSelected(null)};
  const kpis=[["전체 인증","10,127건",QrCode,"blue"],["오늘 인증","448건",Clock3,"indigo"],["인증 성공","402건",CheckCircle2,"green"],["인증 실패","46건",XCircle,"gray"],["중복 시도","17건",CircleHelp,"amber"],["이상 인증 의심","9건",ShieldAlert,"rose"]] as const;

  return <div className={`app-shell ${collapsed?"is-collapsed":""}`}>
    <aside className="sidebar"><div className="brand"><div className="brand-mark">A</div><div className="brand-copy"><strong>AOS</strong><span>TRAVEL ERP</span></div><button className="collapse" onClick={()=>setCollapsed(!collapsed)} aria-label="사이드바 접기">‹</button></div><nav aria-label="관리자 메뉴">{menu.map(item=><div className="nav-group" key={item.label}><button className={`nav-item ${item.label==="스탬프투어 관리"?"active":""}`} onClick={()=>item.label==="대시보드"?window.location.assign("/"):item.children?toggleMenu(item.label):act(`${item.label} 화면으로 이동합니다.`)}><span className="nav-icon">{item.icon==="qr"?<QrCode size={16}/>:item.icon}</span><span className="nav-label">{item.label}</span>{item.children&&<span className={`chevron ${expanded.includes(item.label)?"open":""}`}>⌄</span>}</button>{item.children&&expanded.includes(item.label)&&!collapsed&&<div className="subnav">{item.children.map(child=><button key={child} className={child==="인증 이력"?"current":""} onClick={()=>goChild(child)}>{child}</button>)}</div>}</div>)}</nav><div className="sidebar-help"><span className="nav-icon">?</span><div><strong>업무지원센터</strong><p>평일 09:00–18:00</p></div></div></aside>
    <div className="workspace"><header className="topbar"><div className="breadcrumb"><span>스탬프투어 관리</span><b>/</b><strong>인증 이력</strong></div><div className="top-actions"><label className="search"><span>⌕</span><input aria-label="빠른 검색" placeholder="예약번호, 고객명, 상품명 검색"/><kbd>⌘ K</kbd></label><button className="icon-btn">?</button><div className="dropdown-wrap"><button className="icon-btn notice" aria-label="알림" onClick={()=>{setNoticeOpen(!noticeOpen);setProfileOpen(false)}}>♢<i>5</i></button>{noticeOpen&&<div className="dropdown notice-menu"><div className="drop-head"><strong>알림</strong><button onClick={()=>setNoticeOpen(false)}>모두 읽음</button></div><button><span className="alert-dot warn"/><span>미검수 이상 인증 9건이 있습니다.<small>방금 전</small></span></button></div>}</div><div className="divider"/><div className="dropdown-wrap"><button className="profile" onClick={()=>{setProfileOpen(!profileOpen);setNoticeOpen(false)}}><span className="avatar">장</span><span><b>애비아넥스트</b><small>관리자 장윤호</small></span><em>⌄</em></button>{profileOpen&&<div className="dropdown profile-menu"><button>내 정보</button><button>환경설정</button><hr/><button className="logout">로그아웃</button></div>}</div></div></header>
      <main className="content verification-content"><LiveStampTourPanel section="verifications"/><section className="page-head"><div><h1>인증 이력</h1><p>QR 인증 성공·실패 기록과 중복 또는 비정상 참여를 검수합니다.</p></div><span className="verification-guide"><ShieldCheck size={14}/>관리자 검수 기록은 변경 이력에 보관됩니다.</span></section>
        <section className="verification-kpis">{kpis.map(([title,value,Icon,color])=><div className={`verification-kpi ${color}`} key={title}><span><small>{title}</small><strong>{value}</strong></span><i><Icon size={18}/></i></div>)}</section>
        <section className="panel verification-filter"><div className="verification-filter-grid"><label><span>스탬프투어</span><select value={tour} onChange={event=>setTour(event.target.value)}><option>철원 DMZ 평화관광 스탬프투어</option><option>양평 자연휴양 산책 스탬프투어</option></select></label><label><span>관광지</span><select value={spot} onChange={event=>setSpot(event.target.value)}><option>전체</option>{[...new Set(records.map(row=>row.spot))].map(value=><option key={value}>{value}</option>)}</select></label><label><span>참여자명</span><input value={name} onChange={event=>setName(event.target.value)} placeholder="이름 입력"/></label><label><span>휴대전화번호</span><input value={phone} onChange={event=>setPhone(event.target.value)} placeholder="숫자만 입력"/></label><label className="verification-period"><span>인증기간</span><div><input type="date" value={from} onChange={event=>setFrom(event.target.value)}/><em>~</em><input type="date" value={to} onChange={event=>setTo(event.target.value)}/></div></label><label><span>인증결과</span><select value={result} onChange={event=>setResult(event.target.value)}><option>전체</option><option>정상 인증</option><option>인증 실패</option></select></label><label><span>이상 유형</span><select value={anomaly} onChange={event=>setAnomaly(event.target.value)}><option>전체</option>{[...new Set(records.map(row=>row.anomaly))].map(value=><option key={value}>{value}</option>)}</select></label><label><span>검수상태</span><select value={review} onChange={event=>setReview(event.target.value)}><option>전체</option><option>미검수</option><option>정상</option><option>부정</option><option>확인 보류</option></select></label></div><div className="verification-filter-actions"><button className="secondary" onClick={reset}><FilterX size={14}/>조건 초기화</button><button className="primary" onClick={search}><Search size={14}/>검색</button></div></section>
        <section className="panel verification-list-panel"><div className="verification-list-head"><div><strong>인증 이력 <b>{filtered.length}</b>건</strong><span>최근 인증순</span></div><p><i className="normal"/>정상 <i className="caution"/>주의 <i className="risk"/>위험</p></div><div className="verification-table-wrap"><table className="verification-table"><thead><tr>{["인증번호","인증일시","참여자","관광지","인증결과","관광지와의 거리","기기정보","IP","이상 유형","검수상태","관리"].map(title=><th key={title}>{title}</th>)}</tr></thead><tbody>{visible.length?visible.map(row=><tr key={row.id}><td className="verification-number">{row.number}</td><td className="verification-date">{row.date}</td><td className="verification-person"><b>{row.participant}</b><small>{maskPhone(row.phone)}</small></td><td className="verification-spot"><b>{row.spot}</b><small>{row.spotCode}</small></td><td><span className={`verification-result ${row.result==="정상 인증"?"success":"failed"}`}>{row.result==="정상 인증"?<CheckCircle2 size={11}/>:<XCircle size={11}/>} {row.result}</span></td><td><span className={`distance-value ${row.distanceM>100?"outside":""}`}><MapPin size={11}/>{row.distance}</span></td><td className="device-cell">{row.deviceType==="mobile"?<Smartphone size={12}/>:<Laptop size={12}/>}<span>{row.device}</span></td><td className="ip-cell">{row.ip}</td><td><span className={`anomaly-type ${anomalyClass(row.anomaly)}`}>{row.anomaly!=="없음"&&<AlertTriangle size={11}/>} {row.anomaly}</span></td><td><span className={`review-status ${row.review==="정상"?"done":row.review==="부정"?"fraud":row.review==="확인 보류"?"hold":"pending"}`}>{row.review}</span></td><td><button className="verification-detail-button" onClick={()=>openDrawer(row)}><Eye size={13}/>상세</button></td></tr>):<tr><td colSpan={11}><div className="verification-empty"><QrCode size={29}/><strong>검색 조건에 맞는 인증 이력이 없습니다.</strong><p>조건을 변경하거나 초기화해 주세요.</p><button className="secondary" onClick={reset}><FilterX size={13}/>조건 초기화</button></div></td></tr>}</tbody></table></div><div className="participant-footer"><span>총 {filtered.length}건 중 {visible.length}건 표시</span><div className="pagination"><button disabled={page===1} onClick={()=>setPage(value=>Math.max(1,value-1))}>‹</button>{Array.from({length:totalPages},(_,index)=><button key={index+1} className={page===index+1?"active":""} onClick={()=>setPage(index+1)}>{index+1}</button>)}<button disabled={page===totalPages} onClick={()=>setPage(value=>Math.min(totalPages,value+1))}>›</button></div><div/></div></section><footer>© 2026 AOS Travel ERP · AviaNext</footer>
      </main></div>
    {selected&&<div className="verification-drawer-layer" role="dialog" aria-modal="true" aria-label="인증 상세 검수"><button className="drawer-backdrop" onClick={()=>setSelected(null)} aria-label="닫기"/><aside className="verification-drawer"><div className="drawer-head"><div><span className={`verification-result ${selected.result==="정상 인증"?"success":"failed"}`}>{selected.result}</span><h2>인증 상세 검수</h2><p>{selected.number}</p></div><button onClick={()=>setSelected(null)} aria-label="닫기">×</button></div><div className="drawer-record-nav"><button disabled={filtered.findIndex(row=>row.id===selected.id)===0} onClick={()=>moveRecord(-1)}><ChevronLeft size={13}/>이전 기록</button><span>{filtered.findIndex(row=>row.id===selected.id)+1} / {filtered.length}</span><button disabled={filtered.findIndex(row=>row.id===selected.id)===filtered.length-1} onClick={()=>moveRecord(1)}>다음 기록<ChevronRight size={13}/></button></div><div className="drawer-scroll"><section><h3>참여자·관광지 정보</h3><dl><div><dt>참여자</dt><dd>{selected.participant} · {maskPhone(selected.phone)}</dd></div><div><dt>관광지</dt><dd>{selected.spot} · {selected.spotCode}</dd></div><div><dt>인증 일시</dt><dd>{selected.date}</dd></div></dl></section><section><h3>GPS 위치 확인</h3><div className="verification-map"><MapPin size={20}/><span><b>인증 위치</b><small>{selected.lat}, {selected.lng}</small></span><i/></div><dl><div><dt>관광지 좌표</dt><dd>{selected.spotLat}, {selected.spotLng}</dd></div><div><dt>측정 거리</dt><dd className={selected.distanceM>100?"danger-text":"ok-text"}>{selected.distance} · 허용 반경 100m</dd></div></dl></section><section><h3>기기 및 접속정보</h3><dl><div><dt>기기정보</dt><dd>{selected.device}</dd></div><div><dt>IP 주소</dt><dd>{selected.ip}</dd></div><div><dt>이상 유형</dt><dd><span className={`anomaly-type ${anomalyClass(selected.anomaly)}`}>{selected.anomaly}</span></dd></div></dl></section><section className="review-form"><h3>관리자 판정</h3><div className="judgement-options">{(["정상","부정","확인 보류"] as const).map(value=><button key={value} className={`${judgement===value?"selected":""} ${value==="부정"?"fraud":value==="확인 보류"?"hold":"normal"}`} onClick={()=>setJudgement(value)}>{value==="정상"?<ShieldCheck size={15}/>:value==="부정"?<ShieldAlert size={15}/>:<Flag size={15}/>}<span><b>{value}</b><small>{value==="정상"?"유효한 인증으로 승인":value==="부정"?"부정 인증으로 판정":"추가 확인 후 판정"}</small></span></button>)}</div><label><span>처리 사유 <b>*</b></span><textarea value={reason} onChange={event=>{setReason(event.target.value);setReasonError(false)}} placeholder="판정 근거와 처리 사유를 입력해 주세요."/><small className={reasonError?"error":""}>{reasonError?"처리 사유를 입력해 주세요.":"판정과 함께 관리자 검수 이력에 기록됩니다."}</small></label><label><span>관리자 메모</span><textarea value={memo} onChange={event=>setMemo(event.target.value)} placeholder="추가 확인 사항 또는 내부 메모를 입력하세요."/></label></section></div><div className="drawer-actions"><button className="secondary" onClick={()=>setSelected(null)}>취소</button><button className="primary" onClick={saveReview}>검수 결과 저장</button></div></aside></div>}
    {toast&&<div className="toast"><span>✓</span>{toast}</div>}
  </div>;
}
