"use client";

import { useState } from "react";
import { AlertTriangle, CalendarDays, ChevronRight, CirclePause, CirclePlay, Clock3, Eye, Gift, MapPin, Pencil, QrCode, RefreshCw, ShieldAlert, TicketCheck, Trophy, UserCheck, Users } from "lucide-react";

const menu=[
  {icon:"▦",label:"대시보드"},{icon:"◇",label:"상품관리",children:["상품목록","상품등록","일정표관리","요금관리"]},{icon:"▤",label:"예약관리",children:["예약접수현황","예약달력"]},{icon:"₩",label:"결제관리",children:["결제현황","취소/환불"]},{icon:"⇄",label:"정산관리",children:["정산현황","판매점정산","공급사정산"]},{icon:"♙",label:"회원관리",children:["웹회원","관리자/직원","그룹/권한"]},{icon:"▣",label:"판매점관리"},{icon:"⌂",label:"거래처관리"},{icon:"qr",label:"스탬프투어 관리",children:["스탬프투어 목록","관광지 관리","참여자·진행현황","인증 이력","완주·경품 관리","통계"]},{icon:"▥",label:"통계관리"},{icon:"◎",label:"운영관리",children:["팝업관리","알림관리","알림톡"]},{icon:"⚙",label:"시스템설정",children:["홈페이지설정","결제설정","기본설정"]},
];

const spots=[
  {name:"고석정",code:"SPOT-001",address:"강원특별자치도 철원군 동송읍 태봉로 1825",qr:"정상",today:86,total:1842,status:"운영 중"},{name:"소이산 모노레일",code:"SPOT-002",address:"강원특별자치도 철원군 철원읍 금강산로 262",qr:"정상",today:74,total:1621,status:"운영 중"},{name:"DMZ 두루미평화타운",code:"SPOT-003",address:"강원특별자치도 철원군 동송읍 양지2길 15-21",qr:"정상",today:59,total:1398,status:"운영 중"},{name:"월정리역",code:"SPOT-004",address:"강원특별자치도 철원군 철원읍 두루미로 1882",qr:"점검 필요",today:21,total:1106,status:"일시중지"},{name:"철원역사문화공원",code:"SPOT-005",address:"강원특별자치도 철원군 철원읍 금강산로 112",qr:"정상",today:65,total:1284,status:"운영 중"},{name:"백마고지 전적지",code:"SPOT-006",address:"강원특별자치도 철원군 철원읍 대마1길 72",qr:"정상",today:43,total:957,status:"운영 중"},{name:"직탕폭포",code:"SPOT-007",address:"강원특별자치도 철원군 동송읍 직탕길 86",qr:"정상",today:48,total:886,status:"운영 중"},{name:"은하수교",code:"SPOT-008",address:"강원특별자치도 철원군 동송읍 장흥리 725-12",qr:"정상",today:52,total:1033,status:"운영 중"},
];

const verifications=[
  ["박서윤","고석정","18:36","정상"],["최민지","은하수교","18:28","정상"],["김도현","소이산 모노레일","18:27","정상"],["정유진","월정리역","18:19","확인 필요"],
];
const rewards=[
  ["김태훈","완주","18:18","8곳 인증"],["오수빈","경품 신청","17:52","배송지 입력"],["한지민","완주","17:43","6곳 인증"],["윤준호","경품 신청","17:20","신청 완료"],
];
const anomalies=[
  ["동일 위치 반복 인증","3건","최근 1시간","danger"],["허용 반경 외 인증","4건","오늘","warn"],["짧은 시간 다중 인증","2건","오늘","warn"],["QR 상태 점검 필요","1곳","월정리역","info"],
];

export default function StampTourDetailPage(){
  const [collapsed,setCollapsed]=useState(false);const [expanded,setExpanded]=useState(["스탬프투어 관리"]);const [paused,setPaused]=useState(false);const [toast,setToast]=useState("");const [profileOpen,setProfileOpen]=useState(false);const [noticeOpen,setNoticeOpen]=useState(false);const [updated,setUpdated]=useState("2026.08.19 18:40");
  const act=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2200)};
  const toggleMenu=(label:string)=>setExpanded(v=>v.includes(label)?v.filter(x=>x!==label):[...v,label]);
  const goChild=(child:string)=>child==="스탬프투어 목록"?window.location.assign("/stamp-tours"):child==="관광지 관리"?window.location.assign("/stamp-tours/attractions"):child==="참여자·진행현황"?window.location.assign("/stamp-tours/participants"):child==="인증 이력"?window.location.assign("/stamp-tours/verifications"):child==="완주·경품 관리"?window.location.assign("/stamp-tours/rewards"):child==="통계"?window.location.assign("/stamp-tours/statistics"):child==="상품목록"?window.location.assign("/products"):act(`${child} 화면은 다음 단계에서 제공될 예정입니다.`);
  const kpis=[
    ["전체 참여자","1,248명","누적 참여자",Users,"blue"],["오늘 신규 참여자","73명","전일 대비 +12명",UserCheck,"green"],["누적 인증","10,127건","오늘 448건",QrCode,"indigo"],["완주자","386명","오늘 29명",Trophy,"purple"],["완주율","30.9%","전체 참여자 기준",TicketCheck,"sky"],["경품 신청자","214명","미처리 18명",Gift,"amber"],["이상 인증","9건","확인 필요",ShieldAlert,"red"],
  ] as const;

  return <div className={`app-shell ${collapsed?"is-collapsed":""}`}><aside className="sidebar"><div className="brand"><div className="brand-mark">A</div><div className="brand-copy"><strong>AOS</strong><span>TRAVEL ERP</span></div><button className="collapse" onClick={()=>setCollapsed(!collapsed)} aria-label="사이드바 접기">‹</button></div><nav aria-label="관리자 메뉴">{menu.map(item=><div className="nav-group" key={item.label}><button className={`nav-item ${item.label==="스탬프투어 관리"?"active":""}`} onClick={()=>item.label==="대시보드"?window.location.assign("/"):item.children?toggleMenu(item.label):act(`${item.label} 화면으로 이동합니다.`)}><span className="nav-icon">{item.icon==="qr"?<QrCode size={16} strokeWidth={1.8}/>:item.icon}</span><span className="nav-label">{item.label}</span>{item.children&&<span className={`chevron ${expanded.includes(item.label)?"open":""}`}>⌄</span>}</button>{item.children&&expanded.includes(item.label)&&!collapsed&&<div className="subnav">{item.children.map(child=><button key={child} className={child==="스탬프투어 목록"?"current":""} onClick={()=>goChild(child)}>{child}</button>)}</div>}</div>)}</nav><div className="sidebar-help"><span className="nav-icon">?</span><div><strong>업무지원센터</strong><p>평일 09:00–18:00</p></div></div></aside>

    <div className="workspace"><header className="topbar"><div className="breadcrumb"><span>스탬프투어 관리</span><b>/</b><span>스탬프투어 목록</span><b>/</b><strong>상세</strong></div><div className="top-actions"><label className="search"><span>⌕</span><input aria-label="빠른 검색" placeholder="예약번호, 고객명, 상품명 검색"/><kbd>⌘ K</kbd></label><button className="icon-btn" onClick={()=>act("업무지원센터를 엽니다.")}>?</button><div className="dropdown-wrap"><button className="icon-btn notice" aria-label="알림" onClick={()=>{setNoticeOpen(!noticeOpen);setProfileOpen(false)}}>♢<i>5</i></button>{noticeOpen&&<div className="dropdown notice-menu"><div className="drop-head"><strong>알림</strong><button onClick={()=>setNoticeOpen(false)}>모두 읽음</button></div><button><span className="alert-dot warn"></span><span>이상 인증 9건을 확인해 주세요.<small>방금 전</small></span></button></div>}</div><div className="divider"/><div className="dropdown-wrap"><button className="profile" onClick={()=>{setProfileOpen(!profileOpen);setNoticeOpen(false)}}><span className="avatar">장</span><span><b>애비아넥스트</b><small>관리자 장윤호</small></span><em>⌄</em></button>{profileOpen&&<div className="dropdown profile-menu"><button>내 정보</button><button>환경설정</button><hr/><button className="logout">로그아웃</button></div>}</div></div></header>

      <main className="content detail-content"><section className="detail-hero panel"><div className="detail-hero-main"><div className="tour-symbol"><QrCode size={25}/></div><div><div className="tour-code-row"><span>ST-CHW-2026-001</span><span className={`badge ${paused?"warn":"success"}`}>{paused?"일시중지":"운영 중"}</span><span className="public-badge"><Eye size={12}/>공개</span></div><h1>철원 DMZ 평화관광 스탬프투어</h1><p>운영기간 2026.08.01~2026.10.31 · 관광지 8곳 · 8곳 중 5곳 이상 인증</p></div></div><div className="detail-actions"><button className="secondary" onClick={()=>window.location.assign("/stamp-tours")}>목록</button><button className="secondary" onClick={()=>window.location.assign("/stamp-tours/1/edit")}><Pencil size={14}/>수정</button><button className={paused?"resume-btn":"pause-btn"} onClick={()=>{setPaused(!paused);act(paused?"투어 운영을 재개했습니다.":"투어 운영을 일시중지했습니다.")}}>{paused?<CirclePlay size={14}/>:<CirclePause size={14}/>} {paused?"운영 재개":"운영 일시중지"}</button></div></section>

      <section className="detail-kpi-grid">{kpis.map(([title,value,note,Icon,color])=><button className={`detail-kpi ${color}`} key={title} onClick={()=>act(`${title} 관련 현황을 확인합니다.`)}><span className="detail-kpi-icon"><Icon size={17}/></span><span><small>{title}</small><strong>{value}</strong><em>{note}</em></span><ChevronRight size={14}/></button>)}</section>

      <section className="panel operation-panel"><div className="panel-head"><div><h2>운영정보</h2><p>현재 적용 중인 투어 운영 기준</p></div><div className="updated"><Clock3 size={12}/>최종 업데이트 {updated}<button onClick={()=>{setUpdated("2026.08.19 18:42");act("운영정보를 새로고침했습니다.")}} aria-label="새로고침"><RefreshCw size={13}/></button></div></div><div className="operation-info">{[["운영기간","2026.08.01 ~ 2026.10.31",CalendarDays],["운영지역","강원특별자치도 철원군",MapPin],["관광지 수","총 8곳",QrCode],["완주조건","8곳 중 5곳 이상 인증",Trophy],["인증 반경","관광지 기준 100m",TicketCheck],["경품 신청기간","2026.08.01 ~ 2026.11.07",Gift],["담당자","관광마케팅팀 · 김태인",UserCheck]].map(([label,value,Icon])=><div key={String(label)}><span><Icon size={14}/>{String(label)}</span><strong>{String(value)}</strong></div>)}</div></section>

      <section className="panel spot-progress-panel"><div className="panel-head"><div><h2>관광지 진행 요약 <span className="count">8</span></h2><p>오늘 QR 및 인증 운영상태를 관광지별로 확인합니다.</p></div><button className="text-btn" onClick={()=>window.location.assign("/stamp-tours/attractions")}>관광지 관리 →</button></div><div className="spot-table-wrap"><table className="spot-table"><colgroup><col className="spot-col-no"/><col className="spot-col-name"/><col className="spot-col-address"/><col className="spot-col-qr"/><col className="spot-col-count"/><col className="spot-col-count"/><col className="spot-col-status"/></colgroup><thead><tr>{["NO.","관광지명","주소","QR 상태","오늘 인증","누적 인증","운영상태"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{spots.map((spot,i)=><tr key={spot.code}><td>{i+1}</td><td><b>{spot.name}</b><small>{spot.code}</small></td><td className="spot-address"><MapPin size={13}/><span>{spot.address}</span></td><td><span className={`qr-health ${spot.qr==="정상"?"ok":"check"}`}><i/>{spot.qr}</span></td><td className="number"><b>{spot.today.toLocaleString()}건</b></td><td className="number">{spot.total.toLocaleString()}건</td><td><span className={`badge ${spot.status==="운영 중"?"success":"warn"}`}>{spot.status}</span></td></tr>)}</tbody></table></div></section>

      <section className="activity-section"><div className="section-title-row"><div><h2>최근 활동</h2><p>실시간 운영 흐름과 확인이 필요한 항목입니다.</p></div><span><i/>실시간 갱신</span></div><div className="activity-grid">
        <section className="panel activity-card"><div className="activity-head indigo"><span><QrCode size={15}/></span><div><h3>최근 관광지 인증</h3><p>오늘 인증 448건</p></div><button onClick={()=>window.location.assign("/stamp-tours/verifications")}>전체보기</button></div><div className="activity-list">{verifications.map((r,i)=><button key={i} onClick={()=>window.location.assign("/stamp-tours/verifications")}><span className="status-symbol"><QrCode size={13}/></span><span><b>{r[0]}</b><small>{r[1]}</small></span><span><b>{r[2]}</b><small className={r[3]==="확인 필요"?"warn-text":"ok-text"}>{r[3]}</small></span></button>)}</div></section>
        <section className="panel activity-card"><div className="activity-head purple"><span><Trophy size={15}/></span><div><h3>최근 완주·경품 신청</h3><p>완주 386명 · 신청 214명</p></div><button onClick={()=>window.location.assign("/stamp-tours/rewards")}>전체보기</button></div><div className="activity-list">{rewards.map((r,i)=><button key={i} onClick={()=>window.location.assign("/stamp-tours/rewards")}><span className="status-symbol reward"><Gift size={13}/></span><span><b>{r[0]}</b><small>{r[1]}</small></span><span><b>{r[2]}</b><small>{r[3]}</small></span></button>)}</div></section>
        <section className="panel activity-card anomaly-card"><div className="activity-head red"><span><AlertTriangle size={15}/></span><div><h3>확인이 필요한 이상 인증</h3><p>미확인 9건</p></div><button onClick={()=>act("이상 인증 페이지는 다음 단계에서 제공될 예정입니다.")}>전체보기</button></div><div className="anomaly-list">{anomalies.map((r,i)=><button key={i} onClick={()=>act(`${r[0]} 내역을 확인합니다.`)}><i className={r[3]}/><span><b>{r[0]}</b><small>{r[2]}</small></span><strong>{r[1]}</strong><ChevronRight size={13}/></button>)}</div></section>
      </div></section><footer>© 2026 AOS Travel ERP · AviaNext</footer></main></div>{toast&&<div className="toast"><span>✓</span>{toast}</div>}</div>;
}
