import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import { ApiError } from "./http";
const isProduction = process.env.NODE_ENV === "production";
function secret(name: "STAMP_TOUR_HASH_SECRET" | "STAMP_TOUR_ENCRYPTION_KEY" | "STAMP_TOUR_SESSION_SECRET") { const value = process.env[name]; if (value) return value; if (isProduction) throw new ApiError(503, "SECURITY_CONFIG_REQUIRED", `${name} 설정이 필요합니다.`); return `development-only-${name}-change-before-deploy`; }
export function normalizePhone(value: string) { const phone = value.replace(/\D/g, ""); if (!/^01[016789]\d{7,8}$/.test(phone)) throw new ApiError(400, "INVALID_PHONE", "올바른 휴대전화번호를 입력해 주세요."); return phone; }
export function lookupHash(value: string) { return createHmac("sha256", secret("STAMP_TOUR_HASH_SECRET")).update(value).digest("hex"); }
export function tokenHash(value: string) { return createHash("sha256").update(value).digest("hex"); }
function encryptionKey() { return createHash("sha256").update(secret("STAMP_TOUR_ENCRYPTION_KEY")).digest(); }
export function encrypt(value: string) { const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", encryptionKey(), iv); const encrypted = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]); return `${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${encrypted.toString("base64url")}`; }
export function decrypt(value: string) { const [iv, tag, encrypted] = value.split("."); const decipher = createDecipheriv("aes-256-gcm", encryptionKey(), Buffer.from(iv, "base64url")); decipher.setAuthTag(Buffer.from(tag, "base64url")); return Buffer.concat([decipher.update(Buffer.from(encrypted, "base64url")), decipher.final()]).toString("utf8"); }
export function createOpaqueToken(bytes = 32) { return randomBytes(bytes).toString("base64url"); }
export function hashCode(challengeId: string, code: string) { return createHmac("sha256", secret("STAMP_TOUR_HASH_SECRET")).update(`${challengeId}:${code}`).digest("hex"); }
export function safeEqual(a: string, b: string) { const x = Buffer.from(a); const y = Buffer.from(b); return x.length === y.length && timingSafeEqual(x, y); }
export function createParticipantToken(participantId: string) { const payload = Buffer.from(JSON.stringify({ sub: participantId, exp: Date.now() + 1000 * 60 * 60 * 24 * 30 })).toString("base64url"); const signature = createHmac("sha256", secret("STAMP_TOUR_SESSION_SECRET")).update(payload).digest("base64url"); return `${payload}.${signature}`; }
export function participantCookieName(tourCode:string){return `stamp_tour_${tourCode.toLowerCase().replace(/[^a-z0-9]/g,"_")}`;}
export function readParticipantToken(request: Request,tourCode?:string) { const cookie=tourCode?request.headers.get("cookie")?.split(";").map(value=>value.trim()).find(value=>value.startsWith(`${participantCookieName(tourCode)}=`))?.split("=").slice(1).join("="):"";const token = request.headers.get("authorization")?.replace(/^Bearer\s+/i, "") ?? cookie ?? ""; const [payload, signature] = token.split("."); if (!payload || !signature) throw new ApiError(401, "AUTH_REQUIRED", "참여자 인증이 필요합니다."); const expected = createHmac("sha256", secret("STAMP_TOUR_SESSION_SECRET")).update(payload).digest("base64url"); if (!safeEqual(signature, expected)) throw new ApiError(401, "INVALID_SESSION", "유효하지 않은 참여자 인증입니다."); const parsed = JSON.parse(Buffer.from(payload, "base64url").toString()) as { sub: string; exp: number }; if (parsed.exp < Date.now()) throw new ApiError(401, "SESSION_EXPIRED", "참여자 인증이 만료되었습니다."); return parsed.sub; }
export function addDays(days: number) { const date = new Date(); date.setUTCDate(date.getUTCDate() + days); return date.toISOString(); }
