"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import {
  AlertTriangle, CheckCircle2, ChevronDown, ChevronUp, Download, Gift,
  QrCode, RotateCcw, Search, ShieldAlert,
  Trophy, UserCheck, Users,
} from "lucide-react";

const menu=[
  {icon:"▦",label:"대시보드"},{icon:"◇",label:"상품관리",children:["상품목록","상품등록","일정표관리","요금관리"]},{icon:"▤",label:"예약관리",children:["예약접수현황","예약달력"]},{icon:"₩",label:"결제관리",children:["결제현황","취소/환불"]},{icon:"⇄",label:"정산관리",children:["정산현황","판매점정산","공급사정산"]},{icon:"♙",label:"회원관리",children:["웹회원","관리자/직원","그룹/권한"]},{icon:"▣",label:"판매점관리"},{icon:"⌂",label:"거래처관리"},{icon:"qr",label:"스탬프투어 관리",children:["스탬프투어 목록","관광지 관리","참여자·진행현황","인증 이력","완주·경품 관리","통계"]},{icon:"▥",label:"통계관리"},{icon:"◎",label:"운영관리",children:["팝업관리","알림관리","알림톡"]},{icon:"⚙",label:"시스템설정",children:["홈페이지설정","결제설정","기본설정"]},
];

type ProgressStatus="참여 중"|"완주"|"중도 이탈";
type RewardStatus="신청 완료"|"미신청"|"대상 아님"|"지급 완료";
type Participant={
  id:number;number:string;name:string;phone:string;joined:string;recent:string;
  authenticated:number;total:number;status:ProgressStatus;completed:string;
  reward:RewardStatus;anomaly:boolean;anomalyText?:string;
};

const participants:Participant[]=[
  {id:1,number:"STP-20260815-01248",name:"김민수",phone:"010-1234-5678",joined:"2026.08.15 09:58",recent:"2026.08.17 15:36",authenticated:5,total:8,status:"완주",completed:"2026.08.17",reward:"신청 완료",anomaly:false},
  {id:2,number:"PT-2026-01247",name:"이준호",phone:"010-7531-2840",joined:"2026.08.20 09:05",recent:"2026.08.20 13:57",authenticated:3,total:8,status:"참여 중",completed:"-",reward:"대상 아님",anomaly:false},
  {id:3,number:"PT-2026-01246",name:"박서연",phone:"010-9174-6625",joined:"2026.08.20 08:51",recent:"2026.08.20 12:16",authenticated:4,total:8,status:"참여 중",completed:"-",reward:"대상 아님",anomaly:true,anomalyText:"짧은 시간 내 원거리 인증"},
  {id:4,number:"PT-2026-01245",name:"최도윤",phone:"010-3648-0951",joined:"2026.08.19 16:32",recent:"2026.08.20 11:48",authenticated:6,total:8,status:"완주",completed:"2026.08.20",reward:"지급 완료",anomaly:false},
  {id:5,number:"PT-2026-01244",name:"정하은",phone:"010-2286-7319",joined:"2026.08.19 15:10",recent:"2026.08.19 17:22",authenticated:2,total:8,status:"참여 중",completed:"-",reward:"대상 아님",anomaly:false},
  {id:6,number:"PT-2026-01243",name:"윤지후",phone:"010-6842-5017",joined:"2026.08.19 13:44",recent:"2026.08.19 16:05",authenticated:5,total:8,status:"완주",completed:"2026.08.19",reward:"미신청",anomaly:false},
  {id:7,number:"PT-2026-01242",name:"한지민",phone:"010-1953-8472",joined:"2026.08.18 10:28",recent:"2026.08.18 10:31",authenticated:2,total:8,status:"참여 중",completed:"-",reward:"대상 아님",anomaly:true,anomalyText:"동일 기기 반복 인증 의심"},
  {id:8,number:"PT-2026-01241",name:"오현우",phone:"010-8461-3295",joined:"2026.08.17 14:02",recent:"2026.08.17 16:33",authenticated:1,total:8,status:"중도 이탈",completed:"-",reward:"대상 아님",anomaly:false},
  {id:9,number:"PT-2026-01240",name:"송예린",phone:"010-5329-1168",joined:"2026.08.17 11:19",recent:"2026.08.19 15:20",authenticated:7,total:8,status:"완주",completed:"2026.08.19",reward:"신청 완료",anomaly:false},
  {id:10,number:"PT-2026-01239",name:"임시우",phone:"010-7750-4382",joined:"2026.08.16 09:42",recent:"2026.08.18 14:09",authenticated:3,total:8,status:"참여 중",completed:"-",reward:"대상 아님",anomaly:false},
  {id:11,number:"PT-2026-01238",name:"강수아",phone:"010-4018-5573",joined:"2026.08.15 13:15",recent:"2026.08.19 17:41",authenticated:5,total:8,status:"완주",completed:"2026.08.19",reward:"신청 완료",anomaly:true,anomalyText:"GPS 반경 이탈 인증"},
  {id:12,number:"PT-2026-01237",name:"조우진",phone:"010-9382-6044",joined:"2026.08.14 10:06",recent:"2026.08.16 13:12",authenticated:2,total:8,status:"중도 이탈",completed:"-",reward:"대상 아님",anomaly:false},
];

const maskPhone=(phone:string)=>phone.replace(/(\d{3})-(\d{4})-(\d{4})/,"$1-****-$3");

export default function ParticipantProgressPage(){
  const [collapsed,setCollapsed]=useState(false);const [expanded,setExpanded]=useState(["스탬프투어 관리"]);const [toast,setToast]=useState("");const [profileOpen,setProfileOpen]=useState(false);const [noticeOpen,setNoticeOpen]=useState(false);
  const [tour,setTour]=useState("철원 DMZ 평화관광 스탬프투어");const [page,setPage]=useState(1);const [sort,setSort]=useState("최신 참여순");
  const [name,setName]=useState("");const [phone,setPhone]=useState("");const [from,setFrom]=useState("");const [to,setTo]=useState("");const [status,setStatus]=useState("전체");const [reward,setReward]=useState("전체");const [anomaly,setAnomaly]=useState("전체");
  const [applied,setApplied]=useState({name:"",phone:"",from:"",to:"",status:"전체",reward:"전체",anomaly:"전체"});
  const act=(message:string)=>{if(message.startsWith("김민수 참여자 상세")){window.location.assign("/stamp-tours/participants/1");return}setToast(message);window.setTimeout(()=>setToast(""),2300)};
  const toggleMenu=(label:string)=>setExpanded(v=>v.includes(label)?v.filter(x=>x!==label):[...v,label]);
  const goChild=(child:string)=>child==="스탬프투어 목록"?window.location.assign("/stamp-tours"):child==="관광지 관리"?window.location.assign("/stamp-tours/attractions"):child==="참여자·진행현황"?window.location.assign("/stamp-tours/participants"):child==="인증 이력"?window.location.assign("/stamp-tours/verifications"):child==="완주·경품 관리"?window.location.assign("/stamp-tours/rewards"):child==="통계"?window.location.assign("/stamp-tours/statistics"):child==="상품목록"?window.location.assign("/products"):act(`${child} 화면은 다음 단계에서 제공될 예정입니다.`);
  const filtered=useMemo(()=>{
    const result=participants.filter(row=>{
      const joined=row.joined.slice(0,10).replaceAll(".","-");
      return (!applied.name||row.name.includes(applied.name))&&(!applied.phone||row.phone.replaceAll("-","").includes(applied.phone.replaceAll("-","")))&&(!applied.from||joined>=applied.from)&&(!applied.to||joined<=applied.to)&&(applied.status==="전체"||row.status===applied.status)&&(applied.reward==="전체"||row.reward===applied.reward)&&(applied.anomaly==="전체"||(applied.anomaly==="확인 필요"?row.anomaly:!row.anomaly));
    });
    return [...result].sort((a,b)=>sort==="진행률 높은순"?b.authenticated/b.total-a.authenticated/a.total:sort==="최근 인증순"?b.recent.localeCompare(a.recent):sort==="이름순"?a.name.localeCompare(b.name):b.joined.localeCompare(a.joined));
  },[applied,sort]);
  const pageSize=5,totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)),visible=filtered.slice((page-1)*pageSize,page*pageSize);
  const search=()=>{setApplied({name:name.trim(),phone:phone.trim(),from,to,status,reward,anomaly});setPage(1);act("검색 조건을 적용했습니다.")};
  const reset=()=>{setName("");setPhone("");setFrom("");setTo("");setStatus("전체");setReward("전체");setAnomaly("전체");setApplied({name:"",phone:"",from:"",to:"",status:"전체",reward:"전체",anomaly:"전체"});setPage(1);act("검색 조건을 초기화했습니다.")};
  const downloadExcel=()=>{const header=["참여번호","참여자명","휴대전화번호","최초 참여일","최근 인증일","인증 관광지","진행률","참여상태","완주일","경품상태","이상 여부"];const rows=filtered.map(row=>[row.number,row.name,maskPhone(row.phone),row.joined,row.recent,`${row.authenticated}/${row.total}곳`,`${Math.round(row.authenticated/row.total*100)}%`,row.status,row.completed,row.reward,row.anomaly?"확인 필요":"정상"]);const csv="\uFEFF"+[header,...rows].map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="철원-DMZ-스탬프투어-참여자현황.csv";link.click();URL.revokeObjectURL(url);act("참여자 현황 엑셀 파일을 다운로드했습니다.")};
  const summary=[["전체 참여자","1,248명",Users,"blue"],["오늘 신규 참여","37명",UserCheck,"indigo"],["참여 중","807명",QrCode,"cyan"],["완주","386명",Trophy,"green"],["경품 신청","318명",Gift,"purple"],["확인 필요","12건",ShieldAlert,"red"]] as const;

  return <div className={`app-shell ${collapsed?"is-collapsed":""}`}><aside className="sidebar"><div className="brand"><div className="brand-mark">A</div><div className="brand-copy"><strong>AOS</strong><span>TRAVEL ERP</span></div><button className="collapse" onClick={()=>setCollapsed(!collapsed)} aria-label="사이드바 접기">‹</button></div><nav aria-label="관리자 메뉴">{menu.map(item=><div className="nav-group" key={item.label}><button className={`nav-item ${item.label==="스탬프투어 관리"?"active":""}`} onClick={()=>item.label==="대시보드"?window.location.assign("/"):item.children?toggleMenu(item.label):act(`${item.label} 화면으로 이동합니다.`)}><span className="nav-icon">{item.icon==="qr"?<QrCode size={16} strokeWidth={1.8}/>:item.icon}</span><span className="nav-label">{item.label}</span>{item.children&&<span className={`chevron ${expanded.includes(item.label)?"open":""}`}>⌄</span>}</button>{item.children&&expanded.includes(item.label)&&!collapsed&&<div className="subnav">{item.children.map(child=><button key={child} className={child==="참여자·진행현황"?"current":""} onClick={()=>goChild(child)}>{child}</button>)}</div>}</div>)}</nav><div className="sidebar-help"><span className="nav-icon">?</span><div><strong>업무지원센터</strong><p>평일 09:00–18:00</p></div></div></aside>

    <div className="workspace"><header className="topbar"><div className="breadcrumb"><span>스탬프투어 관리</span><b>/</b><strong>참여자·진행현황</strong></div><div className="top-actions"><label className="search"><span>⌕</span><input aria-label="빠른 검색" placeholder="예약번호, 고객명, 상품명 검색"/><kbd>⌘ K</kbd></label><button className="icon-btn" onClick={()=>act("업무지원센터를 엽니다.")}>?</button><div className="dropdown-wrap"><button className="icon-btn notice" aria-label="알림" onClick={()=>{setNoticeOpen(!noticeOpen);setProfileOpen(false)}}>♢<i>5</i></button>{noticeOpen&&<div className="dropdown notice-menu"><div className="drop-head"><strong>알림</strong><button onClick={()=>setNoticeOpen(false)}>모두 읽음</button></div><button><span className="alert-dot warn"/><span>확인이 필요한 이상 인증 12건이 있습니다.<small>방금 전</small></span></button></div>}</div><div className="divider"/><div className="dropdown-wrap"><button className="profile" onClick={()=>{setProfileOpen(!profileOpen);setNoticeOpen(false)}}><span className="avatar">장</span><span><b>애비아넥스트</b><small>관리자 장윤호</small></span><em>⌄</em></button>{profileOpen&&<div className="dropdown profile-menu"><button>내 정보</button><button>환경설정</button><hr/><button className="logout">로그아웃</button></div>}</div></div></header>

      <main className="content participant-content"><section className="page-head participant-page-head"><div><h1>참여자·진행현황</h1><p>참여자별 관광지 인증 진행률과 완주·경품 신청 상태를 한눈에 확인합니다.</p></div><div className="participant-head-actions"><label><span>스탬프투어 선택</span><select value={tour} onChange={e=>{setTour(e.target.value);act(`${e.target.value} 참여자 현황을 불러왔습니다.`)}}><option>철원 DMZ 평화관광 스탬프투어</option><option>양평 자연휴양 산책 스탬프투어</option><option>고양 역사문화길 스탬프투어</option></select></label><button className="excel-button" onClick={downloadExcel}><Download size={14}/>엑셀 다운로드</button></div></section>

        <section className="participant-summary">{summary.map(([title,value,Icon,color])=><div className={`participant-kpi ${color}`} key={title}><span><small>{title}</small><strong>{value}</strong></span><i><Icon size={18}/></i></div>)}</section>

        <section className="panel participant-filter"><div className="participant-filter-grid"><label><span>참여자명</span><input value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder="이름 입력"/></label><label><span>휴대전화번호</span><input value={phone} onChange={e=>setPhone(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder="숫자만 입력"/></label><label className="participant-period"><span>참여기간</span><div><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><em>~</em><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></div></label><label><span>진행상태</span><select value={status} onChange={e=>setStatus(e.target.value)}><option>전체</option><option>참여 중</option><option>완주</option><option>중도 이탈</option></select></label><label><span>경품상태</span><select value={reward} onChange={e=>setReward(e.target.value)}><option>전체</option><option>신청 완료</option><option>미신청</option><option>지급 완료</option><option>대상 아님</option></select></label><label><span>이상 인증 여부</span><select value={anomaly} onChange={e=>setAnomaly(e.target.value)}><option>전체</option><option>확인 필요</option><option>정상</option></select></label></div><div className="participant-filter-actions"><button className="secondary" onClick={reset}><RotateCcw size={14}/>조건 초기화</button><button className="primary" onClick={search}><Search size={14}/>검색</button></div></section>

        <section className="panel participant-list-panel"><div className="participant-list-head"><div><strong>참여자 <b>{filtered.length}</b>명</strong><span>휴대전화번호 전체 표시</span></div><label><span>정렬</span><select value={sort} onChange={e=>{setSort(e.target.value);setPage(1)}}><option>최신 참여순</option><option>진행률 높은순</option><option>최근 인증순</option><option>이름순</option></select></label></div><div className="participant-table-wrap"><table className="participant-table"><thead><tr>{["NO.","참여번호","참여자명","휴대전화번호","최초 참여일","최근 인증일","인증 관광지","진행률","참여상태","완주일","경품상태","이상 여부"].map((title,index)=><th key={title}>{title}{[4,5,7].includes(index)&&<span className="sort-chevrons"><ChevronUp size={8}/><ChevronDown size={8}/></span>}</th>)}</tr></thead><tbody>{visible.length?visible.map((row,index)=>{const progress=Math.round(row.authenticated/row.total*100);return <tr key={row.id}><td>{(page-1)*pageSize+index+1}</td><td className="participant-number">{row.number}</td><td className="participant-name"><Link href="/stamp-tours/participants/1">{row.name}</Link><small>본인인증 완료</small></td><td><span className="participant-phone">{row.phone}</span></td><td className="date-cell">{row.joined}</td><td className="date-cell">{row.recent}</td><td className="spot-count"><b>{row.authenticated}/{row.total}곳</b></td><td><div className="progress-cell"><span><b>{progress}%</b><small>{row.authenticated}/{row.total}곳</small></span><i><em style={{width:`${progress}%`}}/></i></div></td><td><span className={`badge ${row.status==="완주"?"success":row.status==="참여 중"?"info":"gray"}`}>{row.status==="완주"&&<CheckCircle2 size={11}/>} {row.status}</span></td><td className="date-cell">{row.completed}</td><td><span className={`reward-badge ${row.reward==="신청 완료"?"applied":row.reward==="지급 완료"?"paid":row.reward==="미신청"?"waiting":"none"}`}>{row.reward}</span></td><td>{row.anomaly?<button className="anomaly-badge" onClick={()=>act(row.anomalyText||"이상 인증을 확인합니다.")} title={row.anomalyText}><AlertTriangle size={12}/>확인 필요</button>:<span className="normal-status">정상</span>}</td></tr>}) : <tr><td colSpan={12}><div className="participant-empty"><Users size={29}/><strong>검색 조건에 맞는 참여자가 없습니다.</strong><p>조건을 변경하거나 초기화한 뒤 다시 검색해 주세요.</p><button className="secondary" onClick={reset}><RotateCcw size={13}/>조건 초기화</button></div></td></tr>}</tbody></table></div><div className="participant-footer"><span>총 {filtered.length}명 중 {visible.length}명 표시</span><div className="pagination"><button disabled={page===1} onClick={()=>setPage(value=>Math.max(1,value-1))}>‹</button>{Array.from({length:totalPages},(_,index)=><button key={index+1} className={page===index+1?"active":""} onClick={()=>setPage(index+1)}>{index+1}</button>)}<button disabled={page===totalPages} onClick={()=>setPage(value=>Math.min(totalPages,value+1))}>›</button></div><div/></div></section><footer>© 2026 AOS Travel ERP · AviaNext</footer>
      </main>
    </div>{toast&&<div className="toast"><span>✓</span>{toast}</div>}
  </div>;
}
